version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "3005:3005"
  frontend:
    stdin_open: true
    build: ./frontend
    ports:
      - "3000:3000"
  db:
    build: ./mockdbapi
    ports:
      - "3010:3010"